#pragma once
#include "Global.h"

std::string en_US = R"(
    cleaner.info.prefix=§e§l[Cleaner] §r
    cleaner.command.cleaner=Cleaner admin command.
    cleaner.command.despawnSuccess=Successfully despawned %1$s entities.
    cleaner.command.error.noTarget=No targets matched the selector.
    cleaner.command.error.playerOnly=This command can only be executed by players!
    cleaner.command.tps.output=Current server real-time TPS %1$s §r, average TPS %2$s.
    cleaner.command.mspt.output=Current server MSPT %1$s.
    cleaner.command.clean.output=Clean task successfully initiated!
    cleaner.command.voteclean=Initiate entity clean vote.
    cleaner.command.despawntime=Despawn time for items set to %1$s game ticks.
    cleaner.output.count1=The system will automatically clean server entities in %1$s seconds!
    cleaner.output.count2=Attention! The system will automatically clean server entities in %1$s seconds!
    cleaner.output.finish=Cleaning complete! A total of %1$s entities have been cleaned this time.
    cleaner.output.opClean=Admin has enabled server entity cleaning.
    cleaner.output.reload=Cleaner mod reloaded. Some configurations may require a server restart to take effect.
    cleaner.output.triggerAutoCleanCount=Too many server entities detected! There are %1$s cleanable entities currently on the server. Auto-clean program has been activated.
    cleaner.output.triggerAutoCleanTps=Low TPS detected! Server average TPS %1$s\nClean program has been initiated.
    cleaner.vote.cooldown=Vote cleaning cooldown...
    cleaner.vote.cancel=Vote canceled!
    cleaner.vote.confirmNo=Think again
    cleaner.vote.confirmOk=Initiate vote
    cleaner.vote.confirmTubtitle=Do you want to initiate a clean vote?
    cleaner.vote.accept=You have agreed to entity cleaning.
    cleaner.vote.deny=You have declined entity cleaning.
    cleaner.vote.no=Deny
    cleaner.vote.ok=Agree
    cleaner.vote.subtitle=%1$s lunched a clean vote.\n\n Do you agree to clean server entities now?
    cleaner.vote.timeout=Vote has expired!
    cleaner.vote.succeed=Vote cleaning successful!
    cleaner.vote.failed=Vote cleaning did not passed!
    cleaner.vote.title=Vote Cleaning
    cleaner.vote.voted=You have been voted!
    cleaner.vote.voteMessage=%1$s lunched a clean vote. If you agree cleaning entities but did not received a form, please type command /voteclean to vote.
    cleaner.form.main.title=§e§lCleaner§r - Main Menu
    cleaner.form.main.context=Select entity category to clean:
    cleaner.form.main.runtime=Loaded Entities
    cleaner.form.main.unload=Unloaded Entities
    cleaner.form.common.button=%1$s\n§3%2$s
    cleaner.form.runtime.title=§e§lCleaner§r - Loaded Entity Manager
    cleaner.form.runtime.content=Select loaded entity to clean:
    cleaner.form.unload.title=§e§lCleaner§r - Unloaded Entity Manager
    cleaner.form.unload.content=Select unloaded entity to clean:
    cleaner.form.unload.updating=§2Updating...§r\nIf your world contains many entities, this may take §b a long time (~20k entities/min)§r. You can close this panel first; you'll be notified when the update finishes.
    cleaner.form.unload.updated=Last updated: §b%1$s§r\n§eData may be out of sync. Click "Refresh" to update. Max 1 refresh per 10 minutes.\n§c§lWarning: Cleaning unloaded entities will force-remove ALL of them, including named, tamed, and ignored ones. Proceed with caution.
    cleaner.form.unload.refresh=Refresh
    cleaner.unload.updated.msg=§e§lUnloaded entity list§r has finished loading
    cleaner.unload.update.warn=§g§lUnloaded entity list is already updating, cannot trigger again§r
    cleaner.unload.updated.warn=§g§lUnloaded entity list refresh too frequent (max once per 10 min)§r
    cleaner.form.setting.title=§e§lCleaner§r - Clean Options
    cleaner.form.setting.content=Deleting entities\n§b%1$s (%2$s)\n§eTotal: %3$s
    cleaner.form.setting.cleanTamed=Clean Tamed Mobs
    cleaner.form.setting.cleanTrusting=Clean Trusted Mobs
    cleaner.form.setting.cleanCustomName=Clean Named Mobs
    cleaner.form.setting.cleanTag=Clean Ignore Tagged Mobs
    cleaner.form.setting.cleanItemAge=Clean Fresh Drops
    cleaner.form.setting.cleanItemType=Clean Config-Protected Drops
    cleaner.form.confirm.title=Confirmation
    cleaner.form.confirm.warning=§c§lConfirm dangerous operation:§r\nConfirm §c§lforce §rdeletion of\n§b%1$s (%2$s)\n§eTotal: %3$s ?
    cleaner.form.confirm.important=§u§lConfirm operation:§r\nConfirm deletion of\n§b%1$s (%2$s)\n§eTotal: %3$s ? This will force-remove ALL including named, tamed, config-ignored, etc. Proceed with caution.
    cleaner.form.confirm.confirm=Confirm
    cleaner.form.confirm.cancel=Cancel
    cleaner.confirm.unload.warn=Form is updating, deletion temporarily unavailable
)";

std::string zh_CN = R"(
    cleaner.info.prefix=§e§l[Cleaner] §r
    cleaner.command.cleaner=Cleaner管理员命令。
    cleaner.command.despawnSuccess=已成功清除了 %1$s 个实体
    cleaner.command.error.noTarget=没有与选择器匹配的目标
    cleaner.command.error.playerOnly=该命令只能由玩家执行！
    cleaner.command.tps.output=当前服务器实时TPS %1$s §r，平均TPS %2$s
    cleaner.command.mspt.output=当前服务器实时MSPT %1$s
    cleaner.command.clean.output=已成功启动清理任务！
    cleaner.command.voteclean=发起实体清理投票。
    cleaner.command.despawntime=已成功将物品消失时间设置为 %1$s 游戏刻
    cleaner.output.count1=系统将在 %1$s 秒后自动清理服务器实体！
    cleaner.output.count2=请注意！系统将在 %1$s 秒后自动清理服务器实体！
    cleaner.output.finish=清理完成！本次总共清理了 %1$s 个实体。
    cleaner.output.opClean=管理员启用了服务器实体清理。
    cleaner.output.reload=已重载Cleaner插件，部分配置可能需要重启服务器才能生效。
    cleaner.output.triggerAutoCleanCount=检测到服务器实体过多！！当前服务器存在 %1$s 个可清理实体，已启动自动清理程序。
    cleaner.output.triggerAutoCleanTps=当前服务器TPS过低！！服务器平均TPS %1$s\n系统已启动清理程序。
    cleaner.vote.cooldown=投票清理正在冷却...
    cleaner.vote.cancel=投票已取消！
    cleaner.vote.confirmNo=我再想想
    cleaner.vote.confirmOk=发起投票
    cleaner.vote.confirmTubtitle=你是否要发起投票清理？
    cleaner.vote.accept=你已同意实体清理。
    cleaner.vote.deny=你已拒绝实体清理。
    cleaner.vote.no=拒绝
    cleaner.vote.ok=同意
    cleaner.vote.subtitle=%1$s 发起了服务器实体清理投票！\n\n你是否同意现在清理服务器实体？
    cleaner.vote.timeout=投票已过期！
    cleaner.vote.succeed=投票清理成功！
    cleaner.vote.failed=投票清理未通过。
    cleaner.vote.title=投票清理
    cleaner.vote.voted=你已经投过票了！
    cleaner.vote.voteMessage=%1$s 发起了服务器实体清理投票！如果同意清理但是未收到表单，请输入命令 /voteclean 投票。拒绝清理请忽略此信息。
    cleaner.form.main.title=§e§lCleaner§r 主菜单
    cleaner.form.main.context=选择你要清理的生物种类:
    cleaner.form.main.runtime=已加载生物
    cleaner.form.main.unload=未加载生物
    cleaner.form.common.button=%1$s\n§3%2$s 个
    cleaner.form.runtime.title=§e§lCleaner§r-已加载生物管理
    cleaner.form.runtime.content=选择你要清理的已加载生物:
    cleaner.form.unload.title=§e§lCleaner-未加载生物管理
    cleaner.form.unload.content=选择你要清理的未加载生物:
    cleaner.form.unload.updating=§2正在更新中...§r\n如果您存档中有较多实体，这可能花费§b较长时间(大约2w个生物/分钟)§r。你可以先关闭这个面板, 更新完成后将会通知您。
    cleaner.form.unload.updated=数据最后更新时间:§b %1$s \n§e数据有时不同步，你可以点击刷新按钮进行刷新。每10分钟最多进行一次刷新\n§c§l注意, 清理未加载生物会全部强制清除, 包过有命名, 被驯服等, 请谨慎操作
    cleaner.form.unload.refresh=刷新
    cleaner.unload.updated.msg=§e§l离线生物列表§r已完成加载
    cleaner.unload.update.warn=§g§l离线生物列表正在更新，不能重复触发§r
    cleaner.unload.updated.warn=§g§l离线生物列表更新过频繁，每10分钟最多一次
    cleaner.form.setting.title=§e§lCleaner-清理选项
    cleaner.form.setting.content=正在删除生物\n§b%1$s (%2$s)\n§e共计: %3$s 个
    cleaner.form.setting.cleanItemType=清理配置不清理的掉落物
    cleaner.form.setting.cleanItemAge=清理未达到配置时限的掉落物
    cleaner.form.setting.cleanTag=清理有忽略Tag的生物
    cleaner.form.setting.cleanCustomName=清理有自定义名称的生物
    cleaner.form.setting.cleanTrusting=清理信任玩家的生物
    cleaner.form.setting.cleanTamed=清理被驯服的生物
    cleaner.form.confirm.title=确认消息
    cleaner.form.confirm.warning=§c§l确认危险操作:§r\n确认§c§l强制§r删除生物\n§b%1$s (%2$s)\n§e共计: %3$s 个?
    cleaner.form.confirm.important=§u§l确认操作:§r\n确认删除生物\n§b%1$s (%2$s)\n§e共计: %3$s 个?这会强制全部清除, 包过有命名, 被驯服, 配置忽略等, 请谨慎操作
    cleaner.form.confirm.confirm=确认
    cleaner.form.confirm.cancel=取消
    cleaner.confirm.unload.warn=表单正在更新, 暂时无法删除
)";