on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Update Repo
        run: xmake repo -u

      - name: Update Project
        run: xmake f -a x64 -m release -p windows -v -y

      - name: Build Project
        run: xmake -v -y

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: artifact

      - name: Copy Files
        run: |
          cp LICENSE README.md artifact/

      - name: Compress Artifact
        run: |
          zip -r ../${{ github.event.repository.name }}-windows-x64.zip *
        working-directory: artifact

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-windows-x64.zip
